/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Start */

#ifndef _Included_Start
#define _Included_Start
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Start
 * Method:    sayHello
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Start_sayHello
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
