/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class realHTML_tomcat_connector_JNINatural */

#ifndef _Included_realHTML_tomcat_connector_JNINatural
#define _Included_realHTML_tomcat_connector_JNINatural
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_callNatural
 * Signature: (LrealHTML/tomcat/connector/RH4NParams;)LrealHTML/tomcat/connector/RH4NReturn;
 */
JNIEXPORT jobject JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1callNatural
  (JNIEnv *, jobject, jobject);

/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_printVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1printVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
