/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class realHTML_tomcat_connector_JNINatural */

#ifndef _Included_realHTML_tomcat_connector_JNINatural
#define _Included_realHTML_tomcat_connector_JNINatural
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     realHTML_tomcat_connector_JNINatural
 * Method:    jni_callNatural
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_realHTML_tomcat_connector_JNINatural_jni_1callNatural
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jstring, jobjectArray, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
